### ISSUE TITLE
Boot looping after changing thermistor type

### ISSUE THREAD

**Issue by harveyyau** [mcheah/Marlin4MPMD#10]
Hi,

My Mini Delta has an E3D clone hot end installed, with the ATC Semitec 100K thermistor, which corresponds to Type 5.  After pulling in the latest changes to the project   I had this working using previous builds of Marlin4MPMD.

I've gone back to a completely bare clone of the project except for one change.

-#define TEMP_SENSOR_0 75
+#define TEMP_SENSOR_0 5

Switching the value to 5 leaves the printer in an inconsistent state.  Switching it back to 75 allows the printer to boot.

**Comment by mcheah** [comment]
I use a 12-bit ADC now, so all temperature tables need to be adjusted for 0-4095 codes.  If you add a *4 to every line in the thermistor table it should work correctly

**Comment by harveyyau** [comment]
Thank you!  That fixed it for me.  I really appreciate this project, thanks for keeping me printing.

**Comment by mcheah** [comment]
Feel free to submit a pull request and I'll merge in these changes.
