### ISSUE TITLE
16 microstep

### ISSUE THREAD

**Issue by Knaudler** [mcheah/Marlin4MPMD#14]
Hello
the new 44 original FW uses 16er Microstepping
I want to make a new marlin version (from Marlin4MPMD) with 16er Microstepping 
and want to change the pulleys to 16er (original 14 !)

can I use Arduino IDE to change configuration.h ?
the openstm is very new for me - to difficult ?!
compile with arduino ide for marlin is ok for me

thanks

**Comment by mcheah** [comment]
Just change the M92 settings and save the config to SD card with M500.  Compilation is done through openstm32, not arduino.

**Comment by mcheah** [comment]
Yes.
