### ISSUE TITLE
Homing positions hot end to low

### ISSUE THREAD

**Issue by yezok1** [mcheah/Marlin4MPMD#38]
when homing printer hot end drops 30 mm after completion
not connected to compute or using sd card, homing from printer move menu works fine with stock v 43 firmware

**To Reproduce**
1. Which g-codes can cause this issue?
2. Are you printing from USB or the SD card?
3. Are you using the LCD display to start prints or are you using commands from the USB?
4. What OS are you using?
5. What software are you using?(Cura, Pronterface, Octoprint, Repetier...)
6. Did this work on the stock Malyan firmware?
7. What error message is reported?  Are the LED lights blinkly quickly
8. Post the full-code and status log, if you can.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Software: [Cura, Pronterface, Octoprint, Repetier...]

**Additional context**

**Comment by mcheah** [comment]
I believe what you're describing is the "safe homing" feature of Marlin that prevents your carriages from slamming into the top when doing a XY move at max height.  Regardless, try G28 S0 and see if that fixes your concern.
