### ISSUE TITLE
request for firmware with only heat bed 10 amp fix, no crazy 7x7 matrix auto bed leveling that leaves a ton off pla soft serve ice cream blobs all over print bed. my printer prints nice but has trouble maintaining 50 degree C in a 25 degree C room

### ISSUE THREAD

**Issue by yezok1** [mcheah/Marlin4MPMD#44]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by mcheah** [comment]
Run only G29 P0 instead of G29 P1/P2
