### ISSUE TITLE
Start and End G-code

### ISSUE THREAD

**Issue by vk4tnt** [mcheah/Marlin4MPMD#46]
**Is your feature request related to a problem? Please describe.**
After upgrading to firmware_10ALimit_v43+.bin version of Marlin4MPMD - v1.3.3 4/6/2018 and replacing the standard power supply with a regulated 10A supply, the heating issues for ABS were mostly fixed. Thanks for the mod. There are still some problems with the leveling routine causing impurities on the heated bed and taking very long.
**Describe the solution you'd like**
Could you please advise if you have Start and End G-code you can recommend for this version of firmware.

**Comment by mcheah** [comment]
There are lots of resources on the wiki:
Long story short, run G29 once manually, save the mesh with M500 then replace G29 in your start gcode with G29 P0.

https://github.com/mcheah/Marlin4MPMD/wiki/Migration#migrating-from-stock-firmware

https://github.com/mcheah/Marlin4MPMD/wiki/Frequently-Asked-Questions

https://github.com/mcheah/Marlin4MPMD/wiki/Calibration
