### ISSUE TITLE
What is your start and stop gcode

### ISSUE THREAD

**Issue by Krishpannze** [mcheah/Marlin4MPMD#49]

**Comment by mcheah** [comment]
Please read the [migration](https://github.com/mcheah/Marlin4MPMD/wiki/Migration) and [FAQ](https://github.com/mcheah/Marlin4MPMD/wiki/Frequently-Asked-Questions) sections of the [wiki](https://github.com/mcheah/Marlin4MPMD/wiki).

The gist is that you replace your previous G29 command with G29 P0.  Other start gcode should be identical to the [main mpminidelta wiki](https://www.mpminidelta.com/starting_ending_g-code_scripts)
