### ISSUE TITLE
They printer seems to calibrate and does all of that ok but when you try to print the first layer is not on the bed and it messes everything up

### ISSUE THREAD

**Issue by Krishpannze** [mcheah/Marlin4MPMD#51]
**Describe the bug**

**To Reproduce**
1. Which g-codes can cause this issue?
2. Are you printing from USB or the SD card?
3. Are you using the LCD display to start prints or are you using commands from the USB?
4. What OS are you using?
5. What software are you using?(Cura, Pronterface, Octoprint, Repetier...)
6. Did this work on the stock Malyan firmware?
7. What error message is reported?  Are the LED lights blinkly quickly
8. Post the full-code and status log, if you can.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Software: [Cura, Pronterface, Octoprint, Repetier...]

**Additional context**

**Comment by mcheah** [comment]
Hi,

FYI, the Issues page is intended for reporting issues and potential bugs related to the Marlin4MPMD firmware, not for general issues with 3D printers.


There are several communities which are more suited for these types of questions, I recommend you check out the following resources and communities:

bit.ly/MPMD101

https://drive.google.com/file/d/1Y-MJosfKOC-cICCFcPCuUAjoaRDEpx5A/view?usp=sharing

https://www.facebook.com/groups/mpminideltaowners/

https://www.reddit.com/r/mpminidelta/
