### ISSUE TITLE
It looks like MP released the source code

### ISSUE THREAD

**Issue by clytle374** [mcheah/Marlin4MPMD#56]
It's not a bug or a feature request.  Just wanted to let people know that supposedly MP released the source code for many of their printers.  Could be handy to developers here. 

https://github.com/Monoprice3DP/MiniV2DeltaSourceCode

Cory

**Comment by mcheah** [comment]
Thanks this is indeed very interesting.  However i very much doubt this is the source code for the stock firmware but rather a port from  marlin 2.0.  Interesting nonetheless.

**Comment by clytle374** [comment]
That is definitely possible. Just wanted to let people know it was out there in case someone could use it as a reference.

**Comment by mcheah** [comment]
For example they include malyanlcd.cpp which was only added to Marlin once we hacked and reverse engineered the v2 and the mini delta
