### ISSUE TITLE
Hotend crashes into print while homing

### ISSUE THREAD

**Issue by moboch** [mcheah/Marlin4MPMD#57]
Sometimes, if I print objects that use the entire height of the build area, the hotend crashes into the printed part while homing. This didn't happen with the Stock Firmware because there, the printhead doesn't move down after triggering the endstops while homing.

**Comment by mcheah** [comment]
It is supposed to be smart enough to detect when a print is above the safe line, but you can try issuing G28 S0 in the start gcode and it'll disable safe homing.  This is not saved in M500 so you'll have to issue it every print.
